FROM golang:1.12.4-alpine3.9
WORKDIR C:\Users\Admin\go\src\docker\services1
COPY . .
# EXPOSE 8080
CMD ["go", "run", "services1.go"]



 
# FROM alpine:latest 
# RUN apk --no-cache add ca-certificates
# WORKDIR C:\Windows 
# COPY --from=builder C:\Users\Admin\go\src\docker\docker .
# EXPOSE 8080
